<?xml version="1.0" encoding="utf-8"?><Database Name="SUNS_CDHA" Class="ThucHienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=APPLE5460;Initial Catalog=SUNS_CDHA;Integrated Security=True" SettingsObjectName="BHYT.Properties.Settings" SettingsPropertyName="SUNS_CDHAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BV_BenhNhan" Member="BV_BenhNhans">
    <Type Name="BV_BenhNhan">
      <Column Name="Ma" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HoTenKhongDau" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThangSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanToc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhThanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuanHuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhuongXa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TTHonnhan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ghichu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NguoiGT" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NoiLamViec" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoBHYT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNoiDKBHYT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DoiTuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiNguonGT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguonGioithieu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SoDu" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="NguoiThanHoTen" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NguoiThanQuanHe" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NguoiThanDienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiThanDiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DaKichHoat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayMoTaiKhoan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianMoTaiKhoan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Para" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Association Name="BV_BenhNhan_BV_PhieuCDHA" Member="BV_PhieuCDHAs" ThisKey="Ma" OtherKey="MaBN" Type="BV_PhieuCDHA" />
    </Type>
  </Table>
  <Table Name="dbo.BV_PhieuCDHA" Member="BV_PhieuCDHAs">
    <Type Name="BV_PhieuCDHA">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDPhieuChiDinhCT" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SoVaoVien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="KhoaPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaBN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiThucHien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DieuDuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KyThuatVien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KyThuatVien_Phu1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KyThuatVien_Phu2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaMau" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HinhAnhJson" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LyDoHuy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="KetLuan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DeNghi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Loai" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LoaiCLS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChanDoanTruocPT" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ChanDoanSauPT" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LoaiPhim" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiThuThuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayKinhCuoi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NS_CapCuu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NS_ChanDoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NS_DieuTri" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NS_GPB" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NS_SinhThiet" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PP_ThuThuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PP_VoCam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SLPhim" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.String" DbType="NChar(14)" CanBeNull="true" />
      <Column Name="NguoiCapNhat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaMauCLS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoAnhChonIn" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CoBHYT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoPhieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BacSiGayMe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="BV_BenhNhan_BV_PhieuCDHA" Member="BV_BenhNhan" ThisKey="MaBN" OtherKey="Ma" Type="BV_BenhNhan" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_LoadDanhSach" Method="sp_LoadDanhSach">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_LoadDanhSachResult">
      <Column Name="Ma" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="HoTenKhongDau" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThangSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanToc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhThanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuanHuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhuongXa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TTHonnhan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ghichu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NguoiGT" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NoiLamViec" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoBHYT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNoiDKBHYT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DoiTuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiNguonGT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguonGioithieu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SoDu" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="NguoiThanHoTen" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NguoiThanQuanHe" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NguoiThanDienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiThanDiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DaKichHoat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayMoTaiKhoan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianMoTaiKhoan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Para" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertBenhNhan" Method="sp_InsertBenhNhan">
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.Int32" DbType="Int" />
    <Parameter Name="ThangSinh" Parameter="thangSinh" Type="System.Int32" DbType="Int" />
    <Parameter Name="NamSinh" Parameter="namSinh" Type="System.Int32" DbType="Int" />
    <Parameter Name="SoDienThoai" Parameter="soDienThoai" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="SoBHYT" Parameter="soBHYT" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaNoiDKBHYT" Parameter="maNoiDKBHYT" Type="System.String" DbType="NVarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
</Database>