#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHYT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SUNS_CDHA")]
	public partial class ThucHienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBV_BenhNhan(BV_BenhNhan instance);
    partial void UpdateBV_BenhNhan(BV_BenhNhan instance);
    partial void DeleteBV_BenhNhan(BV_BenhNhan instance);
    partial void InsertBV_PhieuCDHA(BV_PhieuCDHA instance);
    partial void UpdateBV_PhieuCDHA(BV_PhieuCDHA instance);
    partial void DeleteBV_PhieuCDHA(BV_PhieuCDHA instance);
    #endregion
		
		public ThucHienDataContext() : 
				base(global::BHYT.Properties.Settings.Default.SUNS_CDHAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThucHienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThucHienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThucHienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThucHienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BV_BenhNhan> BV_BenhNhans
		{
			get
			{
				return this.GetTable<BV_BenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<BV_PhieuCDHA> BV_PhieuCDHAs
		{
			get
			{
				return this.GetTable<BV_PhieuCDHA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LoadDanhSach")]
		public ISingleResult<sp_LoadDanhSachResult> sp_LoadDanhSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="Date")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="Date")] System.Nullable<System.DateTime> denNgay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tuNgay, denNgay);
			return ((ISingleResult<sp_LoadDanhSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertBenhNhan")]
		public int sp_InsertBenhNhan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTen", DbType="NVarChar(100)")] string hoTen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgaySinh", DbType="Int")] System.Nullable<int> ngaySinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThangSinh", DbType="Int")] System.Nullable<int> thangSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamSinh", DbType="Int")] System.Nullable<int> namSinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoDienThoai", DbType="NVarChar(20)")] string soDienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GioiTinh", DbType="NVarChar(10)")] string gioiTinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(500)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoBHYT", DbType="NVarChar(50)")] string soBHYT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNoiDKBHYT", DbType="NVarChar(250)")] string maNoiDKBHYT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoTen, ngaySinh, thangSinh, namSinh, soDienThoai, gioiTinh, email, diaChi, soBHYT, maNoiDKBHYT);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BV_BenhNhan")]
	public partial class BV_BenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma;
		
		private System.DateTime _Ngay;
		
		private string _HoTen;
		
		private System.Data.Linq.Binary _Anh;
		
		private string _HoTenKhongDau;
		
		private System.Nullable<int> _NgaySinh;
		
		private System.Nullable<int> _ThangSinh;
		
		private System.Nullable<int> _NamSinh;
		
		private string _DienThoai;
		
		private string _GioiTinh;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _SoCMND;
		
		private string _NgheNghiep;
		
		private string _DanToc;
		
		private string _QuocTich;
		
		private string _TinhThanh;
		
		private string _QuanHuyen;
		
		private string _PhuongXa;
		
		private string _TTHonnhan;
		
		private string _Ghichu;
		
		private string _NguoiGT;
		
		private System.Nullable<bool> _NoiLamViec;
		
		private string _SoBHYT;
		
		private string _MaNoiDKBHYT;
		
		private string _DoiTuong;
		
		private string _LoaiNguonGT;
		
		private string _NguonGioithieu;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private string _MatKhau;
		
		private System.Nullable<decimal> _SoDu;
		
		private string _NguoiThanHoTen;
		
		private string _NguoiThanQuanHe;
		
		private string _NguoiThanDienThoai;
		
		private string _NguoiThanDiaChi;
		
		private System.Nullable<bool> _DaKichHoat;
		
		private string _SoTaiKhoan;
		
		private System.Nullable<System.DateTime> _NgayMoTaiKhoan;
		
		private System.Nullable<System.DateTime> _ThoiGianMoTaiKhoan;
		
		private string _Para;
		
		private EntitySet<BV_PhieuCDHA> _BV_PhieuCDHAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChanging(string value);
    partial void OnMaChanged();
    partial void OnNgayChanging(System.DateTime value);
    partial void OnNgayChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnAnhChanging(System.Data.Linq.Binary value);
    partial void OnAnhChanged();
    partial void OnHoTenKhongDauChanging(string value);
    partial void OnHoTenKhongDauChanged();
    partial void OnNgaySinhChanging(System.Nullable<int> value);
    partial void OnNgaySinhChanged();
    partial void OnThangSinhChanging(System.Nullable<int> value);
    partial void OnThangSinhChanged();
    partial void OnNamSinhChanging(System.Nullable<int> value);
    partial void OnNamSinhChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnNgheNghiepChanging(string value);
    partial void OnNgheNghiepChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnTinhThanhChanging(string value);
    partial void OnTinhThanhChanged();
    partial void OnQuanHuyenChanging(string value);
    partial void OnQuanHuyenChanged();
    partial void OnPhuongXaChanging(string value);
    partial void OnPhuongXaChanged();
    partial void OnTTHonnhanChanging(string value);
    partial void OnTTHonnhanChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnNguoiGTChanging(string value);
    partial void OnNguoiGTChanged();
    partial void OnNoiLamViecChanging(System.Nullable<bool> value);
    partial void OnNoiLamViecChanged();
    partial void OnSoBHYTChanging(string value);
    partial void OnSoBHYTChanged();
    partial void OnMaNoiDKBHYTChanging(string value);
    partial void OnMaNoiDKBHYTChanged();
    partial void OnDoiTuongChanging(string value);
    partial void OnDoiTuongChanged();
    partial void OnLoaiNguonGTChanging(string value);
    partial void OnLoaiNguonGTChanged();
    partial void OnNguonGioithieuChanging(string value);
    partial void OnNguonGioithieuChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnSoDuChanging(System.Nullable<decimal> value);
    partial void OnSoDuChanged();
    partial void OnNguoiThanHoTenChanging(string value);
    partial void OnNguoiThanHoTenChanged();
    partial void OnNguoiThanQuanHeChanging(string value);
    partial void OnNguoiThanQuanHeChanged();
    partial void OnNguoiThanDienThoaiChanging(string value);
    partial void OnNguoiThanDienThoaiChanged();
    partial void OnNguoiThanDiaChiChanging(string value);
    partial void OnNguoiThanDiaChiChanged();
    partial void OnDaKichHoatChanging(System.Nullable<bool> value);
    partial void OnDaKichHoatChanged();
    partial void OnSoTaiKhoanChanging(string value);
    partial void OnSoTaiKhoanChanged();
    partial void OnNgayMoTaiKhoanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMoTaiKhoanChanged();
    partial void OnThoiGianMoTaiKhoanChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianMoTaiKhoanChanged();
    partial void OnParaChanging(string value);
    partial void OnParaChanged();
    #endregion
		
		public BV_BenhNhan()
		{
			this._BV_PhieuCDHAs = new EntitySet<BV_PhieuCDHA>(new Action<BV_PhieuCDHA>(this.attach_BV_PhieuCDHAs), new Action<BV_PhieuCDHA>(this.detach_BV_PhieuCDHAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this.OnMaChanging(value);
					this.SendPropertyChanging();
					this._Ma = value;
					this.SendPropertyChanged("Ma");
					this.OnMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date NOT NULL")]
		public System.DateTime Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKhongDau", DbType="NVarChar(250)")]
		public string HoTenKhongDau
		{
			get
			{
				return this._HoTenKhongDau;
			}
			set
			{
				if ((this._HoTenKhongDau != value))
				{
					this.OnHoTenKhongDauChanging(value);
					this.SendPropertyChanging();
					this._HoTenKhongDau = value;
					this.SendPropertyChanged("HoTenKhongDau");
					this.OnHoTenKhongDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Int")]
		public System.Nullable<int> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThangSinh", DbType="Int")]
		public System.Nullable<int> ThangSinh
		{
			get
			{
				return this._ThangSinh;
			}
			set
			{
				if ((this._ThangSinh != value))
				{
					this.OnThangSinhChanging(value);
					this.SendPropertyChanging();
					this._ThangSinh = value;
					this.SendPropertyChanged("ThangSinh");
					this.OnThangSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Int")]
		public System.Nullable<int> NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="NVarChar(20)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="NVarChar(50)")]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this.OnNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._NgheNghiep = value;
					this.SendPropertyChanged("NgheNghiep");
					this.OnNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(50)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NVarChar(50)")]
		public string TinhThanh
		{
			get
			{
				return this._TinhThanh;
			}
			set
			{
				if ((this._TinhThanh != value))
				{
					this.OnTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TinhThanh = value;
					this.SendPropertyChanged("TinhThanh");
					this.OnTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanHuyen", DbType="NVarChar(50)")]
		public string QuanHuyen
		{
			get
			{
				return this._QuanHuyen;
			}
			set
			{
				if ((this._QuanHuyen != value))
				{
					this.OnQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._QuanHuyen = value;
					this.SendPropertyChanged("QuanHuyen");
					this.OnQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongXa", DbType="NVarChar(50)")]
		public string PhuongXa
		{
			get
			{
				return this._PhuongXa;
			}
			set
			{
				if ((this._PhuongXa != value))
				{
					this.OnPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._PhuongXa = value;
					this.SendPropertyChanged("PhuongXa");
					this.OnPhuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTHonnhan", DbType="NVarChar(100)")]
		public string TTHonnhan
		{
			get
			{
				return this._TTHonnhan;
			}
			set
			{
				if ((this._TTHonnhan != value))
				{
					this.OnTTHonnhanChanging(value);
					this.SendPropertyChanging();
					this._TTHonnhan = value;
					this.SendPropertyChanged("TTHonnhan");
					this.OnTTHonnhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(150)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiGT", DbType="NVarChar(150)")]
		public string NguoiGT
		{
			get
			{
				return this._NguoiGT;
			}
			set
			{
				if ((this._NguoiGT != value))
				{
					this.OnNguoiGTChanging(value);
					this.SendPropertyChanging();
					this._NguoiGT = value;
					this.SendPropertyChanged("NguoiGT");
					this.OnNguoiGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLamViec", DbType="Bit")]
		public System.Nullable<bool> NoiLamViec
		{
			get
			{
				return this._NoiLamViec;
			}
			set
			{
				if ((this._NoiLamViec != value))
				{
					this.OnNoiLamViecChanging(value);
					this.SendPropertyChanging();
					this._NoiLamViec = value;
					this.SendPropertyChanged("NoiLamViec");
					this.OnNoiLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBHYT", DbType="NVarChar(50)")]
		public string SoBHYT
		{
			get
			{
				return this._SoBHYT;
			}
			set
			{
				if ((this._SoBHYT != value))
				{
					this.OnSoBHYTChanging(value);
					this.SendPropertyChanging();
					this._SoBHYT = value;
					this.SendPropertyChanged("SoBHYT");
					this.OnSoBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNoiDKBHYT", DbType="NVarChar(250)")]
		public string MaNoiDKBHYT
		{
			get
			{
				return this._MaNoiDKBHYT;
			}
			set
			{
				if ((this._MaNoiDKBHYT != value))
				{
					this.OnMaNoiDKBHYTChanging(value);
					this.SendPropertyChanging();
					this._MaNoiDKBHYT = value;
					this.SendPropertyChanged("MaNoiDKBHYT");
					this.OnMaNoiDKBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoiTuong", DbType="NVarChar(50)")]
		public string DoiTuong
		{
			get
			{
				return this._DoiTuong;
			}
			set
			{
				if ((this._DoiTuong != value))
				{
					this.OnDoiTuongChanging(value);
					this.SendPropertyChanging();
					this._DoiTuong = value;
					this.SendPropertyChanged("DoiTuong");
					this.OnDoiTuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNguonGT", DbType="NVarChar(50)")]
		public string LoaiNguonGT
		{
			get
			{
				return this._LoaiNguonGT;
			}
			set
			{
				if ((this._LoaiNguonGT != value))
				{
					this.OnLoaiNguonGTChanging(value);
					this.SendPropertyChanging();
					this._LoaiNguonGT = value;
					this.SendPropertyChanged("LoaiNguonGT");
					this.OnLoaiNguonGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguonGioithieu", DbType="NVarChar(150)")]
		public string NguonGioithieu
		{
			get
			{
				return this._NguonGioithieu;
			}
			set
			{
				if ((this._NguonGioithieu != value))
				{
					this.OnNguonGioithieuChanging(value);
					this.SendPropertyChanging();
					this._NguonGioithieu = value;
					this.SendPropertyChanged("NguonGioithieu");
					this.OnNguonGioithieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(150)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDu", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SoDu
		{
			get
			{
				return this._SoDu;
			}
			set
			{
				if ((this._SoDu != value))
				{
					this.OnSoDuChanging(value);
					this.SendPropertyChanging();
					this._SoDu = value;
					this.SendPropertyChanged("SoDu");
					this.OnSoDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanHoTen", DbType="NVarChar(250)")]
		public string NguoiThanHoTen
		{
			get
			{
				return this._NguoiThanHoTen;
			}
			set
			{
				if ((this._NguoiThanHoTen != value))
				{
					this.OnNguoiThanHoTenChanging(value);
					this.SendPropertyChanging();
					this._NguoiThanHoTen = value;
					this.SendPropertyChanged("NguoiThanHoTen");
					this.OnNguoiThanHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanQuanHe", DbType="NVarChar(150)")]
		public string NguoiThanQuanHe
		{
			get
			{
				return this._NguoiThanQuanHe;
			}
			set
			{
				if ((this._NguoiThanQuanHe != value))
				{
					this.OnNguoiThanQuanHeChanging(value);
					this.SendPropertyChanging();
					this._NguoiThanQuanHe = value;
					this.SendPropertyChanged("NguoiThanQuanHe");
					this.OnNguoiThanQuanHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanDienThoai", DbType="NVarChar(50)")]
		public string NguoiThanDienThoai
		{
			get
			{
				return this._NguoiThanDienThoai;
			}
			set
			{
				if ((this._NguoiThanDienThoai != value))
				{
					this.OnNguoiThanDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._NguoiThanDienThoai = value;
					this.SendPropertyChanged("NguoiThanDienThoai");
					this.OnNguoiThanDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanDiaChi", DbType="NVarChar(50)")]
		public string NguoiThanDiaChi
		{
			get
			{
				return this._NguoiThanDiaChi;
			}
			set
			{
				if ((this._NguoiThanDiaChi != value))
				{
					this.OnNguoiThanDiaChiChanging(value);
					this.SendPropertyChanging();
					this._NguoiThanDiaChi = value;
					this.SendPropertyChanged("NguoiThanDiaChi");
					this.OnNguoiThanDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaKichHoat", DbType="Bit")]
		public System.Nullable<bool> DaKichHoat
		{
			get
			{
				return this._DaKichHoat;
			}
			set
			{
				if ((this._DaKichHoat != value))
				{
					this.OnDaKichHoatChanging(value);
					this.SendPropertyChanging();
					this._DaKichHoat = value;
					this.SendPropertyChanged("DaKichHoat");
					this.OnDaKichHoatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTaiKhoan", DbType="NVarChar(50)")]
		public string SoTaiKhoan
		{
			get
			{
				return this._SoTaiKhoan;
			}
			set
			{
				if ((this._SoTaiKhoan != value))
				{
					this.OnSoTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._SoTaiKhoan = value;
					this.SendPropertyChanged("SoTaiKhoan");
					this.OnSoTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMoTaiKhoan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayMoTaiKhoan
		{
			get
			{
				return this._NgayMoTaiKhoan;
			}
			set
			{
				if ((this._NgayMoTaiKhoan != value))
				{
					this.OnNgayMoTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._NgayMoTaiKhoan = value;
					this.SendPropertyChanged("NgayMoTaiKhoan");
					this.OnNgayMoTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianMoTaiKhoan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianMoTaiKhoan
		{
			get
			{
				return this._ThoiGianMoTaiKhoan;
			}
			set
			{
				if ((this._ThoiGianMoTaiKhoan != value))
				{
					this.OnThoiGianMoTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianMoTaiKhoan = value;
					this.SendPropertyChanged("ThoiGianMoTaiKhoan");
					this.OnThoiGianMoTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Para", DbType="NVarChar(5)")]
		public string Para
		{
			get
			{
				return this._Para;
			}
			set
			{
				if ((this._Para != value))
				{
					this.OnParaChanging(value);
					this.SendPropertyChanging();
					this._Para = value;
					this.SendPropertyChanged("Para");
					this.OnParaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BV_BenhNhan_BV_PhieuCDHA", Storage="_BV_PhieuCDHAs", ThisKey="Ma", OtherKey="MaBN")]
		public EntitySet<BV_PhieuCDHA> BV_PhieuCDHAs
		{
			get
			{
				return this._BV_PhieuCDHAs;
			}
			set
			{
				this._BV_PhieuCDHAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BV_PhieuCDHAs(BV_PhieuCDHA entity)
		{
			this.SendPropertyChanging();
			entity.BV_BenhNhan = this;
		}
		
		private void detach_BV_PhieuCDHAs(BV_PhieuCDHA entity)
		{
			this.SendPropertyChanging();
			entity.BV_BenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BV_PhieuCDHA")]
	public partial class BV_PhieuCDHA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<System.Guid> _IDPhieuChiDinhCT;
		
		private string _SoVaoVien;
		
		private System.Nullable<System.DateTime> _Ngay;
		
		private string _KhoaPhong;
		
		private string _MaBN;
		
		private string _MaDV;
		
		private string _NguoiThucHien;
		
		private string _DieuDuong;
		
		private string _KyThuatVien;
		
		private string _KyThuatVien_Phu1;
		
		private string _KyThuatVien_Phu2;
		
		private System.Nullable<System.Guid> _MaMau;
		
		private string _NoiDung;
		
		private string _HinhAnhJson;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private string _LyDoHuy;
		
		private string _KetLuan;
		
		private string _DeNghi;
		
		private System.Nullable<short> _Loai;
		
		private string _LoaiCLS;
		
		private string _ChanDoanTruocPT;
		
		private string _ChanDoanSauPT;
		
		private string _LoaiPhim;
		
		private string _LoaiThuThuat;
		
		private System.Nullable<System.DateTime> _NgayKinhCuoi;
		
		private System.Nullable<bool> _NS_CapCuu;
		
		private System.Nullable<bool> _NS_ChanDoan;
		
		private System.Nullable<bool> _NS_DieuTri;
		
		private System.Nullable<bool> _NS_GPB;
		
		private System.Nullable<bool> _NS_SinhThiet;
		
		private string _PP_ThuThuat;
		
		private string _PP_VoCam;
		
		private System.Nullable<int> _SLPhim;
		
		private string _TrangThai;
		
		private string _NgayCapNhat;
		
		private string _NguoiCapNhat;
		
		private string _MaMauCLS;
		
		private System.Nullable<short> _SoAnhChonIn;
		
		private System.Nullable<int> _STT;
		
		private System.Nullable<bool> _CoBHYT;
		
		private string _SoPhieu;
		
		private string _BacSiGayMe;
		
		private EntityRef<BV_BenhNhan> _BV_BenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnIDPhieuChiDinhCTChanging(System.Nullable<System.Guid> value);
    partial void OnIDPhieuChiDinhCTChanged();
    partial void OnSoVaoVienChanging(string value);
    partial void OnSoVaoVienChanged();
    partial void OnNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChanged();
    partial void OnKhoaPhongChanging(string value);
    partial void OnKhoaPhongChanged();
    partial void OnMaBNChanging(string value);
    partial void OnMaBNChanged();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnNguoiThucHienChanging(string value);
    partial void OnNguoiThucHienChanged();
    partial void OnDieuDuongChanging(string value);
    partial void OnDieuDuongChanged();
    partial void OnKyThuatVienChanging(string value);
    partial void OnKyThuatVienChanged();
    partial void OnKyThuatVien_Phu1Changing(string value);
    partial void OnKyThuatVien_Phu1Changed();
    partial void OnKyThuatVien_Phu2Changing(string value);
    partial void OnKyThuatVien_Phu2Changed();
    partial void OnMaMauChanging(System.Nullable<System.Guid> value);
    partial void OnMaMauChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnHinhAnhJsonChanging(string value);
    partial void OnHinhAnhJsonChanged();
    partial void OnThoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianChanged();
    partial void OnLyDoHuyChanging(string value);
    partial void OnLyDoHuyChanged();
    partial void OnKetLuanChanging(string value);
    partial void OnKetLuanChanged();
    partial void OnDeNghiChanging(string value);
    partial void OnDeNghiChanged();
    partial void OnLoaiChanging(System.Nullable<short> value);
    partial void OnLoaiChanged();
    partial void OnLoaiCLSChanging(string value);
    partial void OnLoaiCLSChanged();
    partial void OnChanDoanTruocPTChanging(string value);
    partial void OnChanDoanTruocPTChanged();
    partial void OnChanDoanSauPTChanging(string value);
    partial void OnChanDoanSauPTChanged();
    partial void OnLoaiPhimChanging(string value);
    partial void OnLoaiPhimChanged();
    partial void OnLoaiThuThuatChanging(string value);
    partial void OnLoaiThuThuatChanged();
    partial void OnNgayKinhCuoiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKinhCuoiChanged();
    partial void OnNS_CapCuuChanging(System.Nullable<bool> value);
    partial void OnNS_CapCuuChanged();
    partial void OnNS_ChanDoanChanging(System.Nullable<bool> value);
    partial void OnNS_ChanDoanChanged();
    partial void OnNS_DieuTriChanging(System.Nullable<bool> value);
    partial void OnNS_DieuTriChanged();
    partial void OnNS_GPBChanging(System.Nullable<bool> value);
    partial void OnNS_GPBChanged();
    partial void OnNS_SinhThietChanging(System.Nullable<bool> value);
    partial void OnNS_SinhThietChanged();
    partial void OnPP_ThuThuatChanging(string value);
    partial void OnPP_ThuThuatChanged();
    partial void OnPP_VoCamChanging(string value);
    partial void OnPP_VoCamChanged();
    partial void OnSLPhimChanging(System.Nullable<int> value);
    partial void OnSLPhimChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnNgayCapNhatChanging(string value);
    partial void OnNgayCapNhatChanged();
    partial void OnNguoiCapNhatChanging(string value);
    partial void OnNguoiCapNhatChanged();
    partial void OnMaMauCLSChanging(string value);
    partial void OnMaMauCLSChanged();
    partial void OnSoAnhChonInChanging(System.Nullable<short> value);
    partial void OnSoAnhChonInChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnCoBHYTChanging(System.Nullable<bool> value);
    partial void OnCoBHYTChanged();
    partial void OnSoPhieuChanging(string value);
    partial void OnSoPhieuChanged();
    partial void OnBacSiGayMeChanging(string value);
    partial void OnBacSiGayMeChanged();
    #endregion
		
		public BV_PhieuCDHA()
		{
			this._BV_BenhNhan = default(EntityRef<BV_BenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhieuChiDinhCT", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IDPhieuChiDinhCT
		{
			get
			{
				return this._IDPhieuChiDinhCT;
			}
			set
			{
				if ((this._IDPhieuChiDinhCT != value))
				{
					this.OnIDPhieuChiDinhCTChanging(value);
					this.SendPropertyChanging();
					this._IDPhieuChiDinhCT = value;
					this.SendPropertyChanged("IDPhieuChiDinhCT");
					this.OnIDPhieuChiDinhCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoVaoVien", DbType="NVarChar(50)")]
		public string SoVaoVien
		{
			get
			{
				return this._SoVaoVien;
			}
			set
			{
				if ((this._SoVaoVien != value))
				{
					this.OnSoVaoVienChanging(value);
					this.SendPropertyChanging();
					this._SoVaoVien = value;
					this.SendPropertyChanged("SoVaoVien");
					this.OnSoVaoVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this.OnNgayChanging(value);
					this.SendPropertyChanging();
					this._Ngay = value;
					this.SendPropertyChanged("Ngay");
					this.OnNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoaPhong", DbType="NVarChar(50)")]
		public string KhoaPhong
		{
			get
			{
				return this._KhoaPhong;
			}
			set
			{
				if ((this._KhoaPhong != value))
				{
					this.OnKhoaPhongChanging(value);
					this.SendPropertyChanging();
					this._KhoaPhong = value;
					this.SendPropertyChanged("KhoaPhong");
					this.OnKhoaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="NVarChar(100)")]
		public string MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					if (this._BV_BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBNChanging(value);
					this.SendPropertyChanging();
					this._MaBN = value;
					this.SendPropertyChanged("MaBN");
					this.OnMaBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="NVarChar(50)")]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThucHien", DbType="NVarChar(50)")]
		public string NguoiThucHien
		{
			get
			{
				return this._NguoiThucHien;
			}
			set
			{
				if ((this._NguoiThucHien != value))
				{
					this.OnNguoiThucHienChanging(value);
					this.SendPropertyChanging();
					this._NguoiThucHien = value;
					this.SendPropertyChanged("NguoiThucHien");
					this.OnNguoiThucHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DieuDuong", DbType="NVarChar(50)")]
		public string DieuDuong
		{
			get
			{
				return this._DieuDuong;
			}
			set
			{
				if ((this._DieuDuong != value))
				{
					this.OnDieuDuongChanging(value);
					this.SendPropertyChanging();
					this._DieuDuong = value;
					this.SendPropertyChanged("DieuDuong");
					this.OnDieuDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KyThuatVien", DbType="NVarChar(50)")]
		public string KyThuatVien
		{
			get
			{
				return this._KyThuatVien;
			}
			set
			{
				if ((this._KyThuatVien != value))
				{
					this.OnKyThuatVienChanging(value);
					this.SendPropertyChanging();
					this._KyThuatVien = value;
					this.SendPropertyChanged("KyThuatVien");
					this.OnKyThuatVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KyThuatVien_Phu1", DbType="NVarChar(50)")]
		public string KyThuatVien_Phu1
		{
			get
			{
				return this._KyThuatVien_Phu1;
			}
			set
			{
				if ((this._KyThuatVien_Phu1 != value))
				{
					this.OnKyThuatVien_Phu1Changing(value);
					this.SendPropertyChanging();
					this._KyThuatVien_Phu1 = value;
					this.SendPropertyChanged("KyThuatVien_Phu1");
					this.OnKyThuatVien_Phu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KyThuatVien_Phu2", DbType="NVarChar(50)")]
		public string KyThuatVien_Phu2
		{
			get
			{
				return this._KyThuatVien_Phu2;
			}
			set
			{
				if ((this._KyThuatVien_Phu2 != value))
				{
					this.OnKyThuatVien_Phu2Changing(value);
					this.SendPropertyChanging();
					this._KyThuatVien_Phu2 = value;
					this.SendPropertyChanged("KyThuatVien_Phu2");
					this.OnKyThuatVien_Phu2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMau", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> MaMau
		{
			get
			{
				return this._MaMau;
			}
			set
			{
				if ((this._MaMau != value))
				{
					this.OnMaMauChanging(value);
					this.SendPropertyChanging();
					this._MaMau = value;
					this.SendPropertyChanged("MaMau");
					this.OnMaMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhJson", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string HinhAnhJson
		{
			get
			{
				return this._HinhAnhJson;
			}
			set
			{
				if ((this._HinhAnhJson != value))
				{
					this.OnHinhAnhJsonChanging(value);
					this.SendPropertyChanging();
					this._HinhAnhJson = value;
					this.SendPropertyChanged("HinhAnhJson");
					this.OnHinhAnhJsonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDoHuy", DbType="NVarChar(500)")]
		public string LyDoHuy
		{
			get
			{
				return this._LyDoHuy;
			}
			set
			{
				if ((this._LyDoHuy != value))
				{
					this.OnLyDoHuyChanging(value);
					this.SendPropertyChanging();
					this._LyDoHuy = value;
					this.SendPropertyChanged("LyDoHuy");
					this.OnLyDoHuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetLuan", DbType="NVarChar(500)")]
		public string KetLuan
		{
			get
			{
				return this._KetLuan;
			}
			set
			{
				if ((this._KetLuan != value))
				{
					this.OnKetLuanChanging(value);
					this.SendPropertyChanging();
					this._KetLuan = value;
					this.SendPropertyChanged("KetLuan");
					this.OnKetLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeNghi", DbType="NVarChar(500)")]
		public string DeNghi
		{
			get
			{
				return this._DeNghi;
			}
			set
			{
				if ((this._DeNghi != value))
				{
					this.OnDeNghiChanging(value);
					this.SendPropertyChanging();
					this._DeNghi = value;
					this.SendPropertyChanged("DeNghi");
					this.OnDeNghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="SmallInt")]
		public System.Nullable<short> Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiCLS", DbType="NVarChar(50)")]
		public string LoaiCLS
		{
			get
			{
				return this._LoaiCLS;
			}
			set
			{
				if ((this._LoaiCLS != value))
				{
					this.OnLoaiCLSChanging(value);
					this.SendPropertyChanging();
					this._LoaiCLS = value;
					this.SendPropertyChanged("LoaiCLS");
					this.OnLoaiCLSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChanDoanTruocPT", DbType="NVarChar(500)")]
		public string ChanDoanTruocPT
		{
			get
			{
				return this._ChanDoanTruocPT;
			}
			set
			{
				if ((this._ChanDoanTruocPT != value))
				{
					this.OnChanDoanTruocPTChanging(value);
					this.SendPropertyChanging();
					this._ChanDoanTruocPT = value;
					this.SendPropertyChanged("ChanDoanTruocPT");
					this.OnChanDoanTruocPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChanDoanSauPT", DbType="NVarChar(500)")]
		public string ChanDoanSauPT
		{
			get
			{
				return this._ChanDoanSauPT;
			}
			set
			{
				if ((this._ChanDoanSauPT != value))
				{
					this.OnChanDoanSauPTChanging(value);
					this.SendPropertyChanging();
					this._ChanDoanSauPT = value;
					this.SendPropertyChanged("ChanDoanSauPT");
					this.OnChanDoanSauPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhim", DbType="NVarChar(50)")]
		public string LoaiPhim
		{
			get
			{
				return this._LoaiPhim;
			}
			set
			{
				if ((this._LoaiPhim != value))
				{
					this.OnLoaiPhimChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhim = value;
					this.SendPropertyChanged("LoaiPhim");
					this.OnLoaiPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiThuThuat", DbType="NVarChar(50)")]
		public string LoaiThuThuat
		{
			get
			{
				return this._LoaiThuThuat;
			}
			set
			{
				if ((this._LoaiThuThuat != value))
				{
					this.OnLoaiThuThuatChanging(value);
					this.SendPropertyChanging();
					this._LoaiThuThuat = value;
					this.SendPropertyChanged("LoaiThuThuat");
					this.OnLoaiThuThuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKinhCuoi", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKinhCuoi
		{
			get
			{
				return this._NgayKinhCuoi;
			}
			set
			{
				if ((this._NgayKinhCuoi != value))
				{
					this.OnNgayKinhCuoiChanging(value);
					this.SendPropertyChanging();
					this._NgayKinhCuoi = value;
					this.SendPropertyChanged("NgayKinhCuoi");
					this.OnNgayKinhCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NS_CapCuu", DbType="Bit")]
		public System.Nullable<bool> NS_CapCuu
		{
			get
			{
				return this._NS_CapCuu;
			}
			set
			{
				if ((this._NS_CapCuu != value))
				{
					this.OnNS_CapCuuChanging(value);
					this.SendPropertyChanging();
					this._NS_CapCuu = value;
					this.SendPropertyChanged("NS_CapCuu");
					this.OnNS_CapCuuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NS_ChanDoan", DbType="Bit")]
		public System.Nullable<bool> NS_ChanDoan
		{
			get
			{
				return this._NS_ChanDoan;
			}
			set
			{
				if ((this._NS_ChanDoan != value))
				{
					this.OnNS_ChanDoanChanging(value);
					this.SendPropertyChanging();
					this._NS_ChanDoan = value;
					this.SendPropertyChanged("NS_ChanDoan");
					this.OnNS_ChanDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NS_DieuTri", DbType="Bit")]
		public System.Nullable<bool> NS_DieuTri
		{
			get
			{
				return this._NS_DieuTri;
			}
			set
			{
				if ((this._NS_DieuTri != value))
				{
					this.OnNS_DieuTriChanging(value);
					this.SendPropertyChanging();
					this._NS_DieuTri = value;
					this.SendPropertyChanged("NS_DieuTri");
					this.OnNS_DieuTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NS_GPB", DbType="Bit")]
		public System.Nullable<bool> NS_GPB
		{
			get
			{
				return this._NS_GPB;
			}
			set
			{
				if ((this._NS_GPB != value))
				{
					this.OnNS_GPBChanging(value);
					this.SendPropertyChanging();
					this._NS_GPB = value;
					this.SendPropertyChanged("NS_GPB");
					this.OnNS_GPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NS_SinhThiet", DbType="Bit")]
		public System.Nullable<bool> NS_SinhThiet
		{
			get
			{
				return this._NS_SinhThiet;
			}
			set
			{
				if ((this._NS_SinhThiet != value))
				{
					this.OnNS_SinhThietChanging(value);
					this.SendPropertyChanging();
					this._NS_SinhThiet = value;
					this.SendPropertyChanged("NS_SinhThiet");
					this.OnNS_SinhThietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PP_ThuThuat", DbType="NVarChar(50)")]
		public string PP_ThuThuat
		{
			get
			{
				return this._PP_ThuThuat;
			}
			set
			{
				if ((this._PP_ThuThuat != value))
				{
					this.OnPP_ThuThuatChanging(value);
					this.SendPropertyChanging();
					this._PP_ThuThuat = value;
					this.SendPropertyChanged("PP_ThuThuat");
					this.OnPP_ThuThuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PP_VoCam", DbType="NVarChar(50)")]
		public string PP_VoCam
		{
			get
			{
				return this._PP_VoCam;
			}
			set
			{
				if ((this._PP_VoCam != value))
				{
					this.OnPP_VoCamChanging(value);
					this.SendPropertyChanging();
					this._PP_VoCam = value;
					this.SendPropertyChanged("PP_VoCam");
					this.OnPP_VoCamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLPhim", DbType="Int")]
		public System.Nullable<int> SLPhim
		{
			get
			{
				return this._SLPhim;
			}
			set
			{
				if ((this._SLPhim != value))
				{
					this.OnSLPhimChanging(value);
					this.SendPropertyChanging();
					this._SLPhim = value;
					this.SendPropertyChanged("SLPhim");
					this.OnSLPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(100)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="NChar(14)")]
		public string NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="NVarChar(50)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this.OnNguoiCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NguoiCapNhat = value;
					this.SendPropertyChanged("NguoiCapNhat");
					this.OnNguoiCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMauCLS", DbType="NVarChar(50)")]
		public string MaMauCLS
		{
			get
			{
				return this._MaMauCLS;
			}
			set
			{
				if ((this._MaMauCLS != value))
				{
					this.OnMaMauCLSChanging(value);
					this.SendPropertyChanging();
					this._MaMauCLS = value;
					this.SendPropertyChanged("MaMauCLS");
					this.OnMaMauCLSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoAnhChonIn", DbType="SmallInt")]
		public System.Nullable<short> SoAnhChonIn
		{
			get
			{
				return this._SoAnhChonIn;
			}
			set
			{
				if ((this._SoAnhChonIn != value))
				{
					this.OnSoAnhChonInChanging(value);
					this.SendPropertyChanging();
					this._SoAnhChonIn = value;
					this.SendPropertyChanged("SoAnhChonIn");
					this.OnSoAnhChonInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoBHYT", DbType="Bit")]
		public System.Nullable<bool> CoBHYT
		{
			get
			{
				return this._CoBHYT;
			}
			set
			{
				if ((this._CoBHYT != value))
				{
					this.OnCoBHYTChanging(value);
					this.SendPropertyChanging();
					this._CoBHYT = value;
					this.SendPropertyChanged("CoBHYT");
					this.OnCoBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="NVarChar(50)")]
		public string SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this.OnSoPhieuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieu = value;
					this.SendPropertyChanged("SoPhieu");
					this.OnSoPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BacSiGayMe", DbType="NVarChar(50)")]
		public string BacSiGayMe
		{
			get
			{
				return this._BacSiGayMe;
			}
			set
			{
				if ((this._BacSiGayMe != value))
				{
					this.OnBacSiGayMeChanging(value);
					this.SendPropertyChanging();
					this._BacSiGayMe = value;
					this.SendPropertyChanged("BacSiGayMe");
					this.OnBacSiGayMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BV_BenhNhan_BV_PhieuCDHA", Storage="_BV_BenhNhan", ThisKey="MaBN", OtherKey="Ma", IsForeignKey=true)]
		public BV_BenhNhan BV_BenhNhan
		{
			get
			{
				return this._BV_BenhNhan.Entity;
			}
			set
			{
				BV_BenhNhan previousValue = this._BV_BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BV_BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BV_BenhNhan.Entity = null;
						previousValue.BV_PhieuCDHAs.Remove(this);
					}
					this._BV_BenhNhan.Entity = value;
					if ((value != null))
					{
						value.BV_PhieuCDHAs.Add(this);
						this._MaBN = value.Ma;
					}
					else
					{
						this._MaBN = default(string);
					}
					this.SendPropertyChanged("BV_BenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_LoadDanhSachResult
	{
		
		private string _Ma;
		
		private System.DateTime _Ngay;
		
		private string _HoTen;
		
		private System.Data.Linq.Binary _Anh;
		
		private string _HoTenKhongDau;
		
		private System.Nullable<int> _NgaySinh;
		
		private System.Nullable<int> _ThangSinh;
		
		private System.Nullable<int> _NamSinh;
		
		private string _DienThoai;
		
		private string _GioiTinh;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _SoCMND;
		
		private string _NgheNghiep;
		
		private string _DanToc;
		
		private string _QuocTich;
		
		private string _TinhThanh;
		
		private string _QuanHuyen;
		
		private string _PhuongXa;
		
		private string _TTHonnhan;
		
		private string _Ghichu;
		
		private string _NguoiGT;
		
		private System.Nullable<bool> _NoiLamViec;
		
		private string _SoBHYT;
		
		private string _MaNoiDKBHYT;
		
		private string _DoiTuong;
		
		private string _LoaiNguonGT;
		
		private string _NguonGioithieu;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private string _MatKhau;
		
		private System.Nullable<decimal> _SoDu;
		
		private string _NguoiThanHoTen;
		
		private string _NguoiThanQuanHe;
		
		private string _NguoiThanDienThoai;
		
		private string _NguoiThanDiaChi;
		
		private System.Nullable<bool> _DaKichHoat;
		
		private string _SoTaiKhoan;
		
		private System.Nullable<System.DateTime> _NgayMoTaiKhoan;
		
		private System.Nullable<System.DateTime> _ThoiGianMoTaiKhoan;
		
		private string _Para;
		
		public sp_LoadDanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this._Ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="Date NOT NULL")]
		public System.DateTime Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Image")]
		public System.Data.Linq.Binary Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this._Anh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKhongDau", DbType="NVarChar(250)")]
		public string HoTenKhongDau
		{
			get
			{
				return this._HoTenKhongDau;
			}
			set
			{
				if ((this._HoTenKhongDau != value))
				{
					this._HoTenKhongDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Int")]
		public System.Nullable<int> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThangSinh", DbType="Int")]
		public System.Nullable<int> ThangSinh
		{
			get
			{
				return this._ThangSinh;
			}
			set
			{
				if ((this._ThangSinh != value))
				{
					this._ThangSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Int")]
		public System.Nullable<int> NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this._DienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="NVarChar(20)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this._SoCMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="NVarChar(50)")]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this._NgheNghiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this._DanToc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(50)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this._QuocTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NVarChar(50)")]
		public string TinhThanh
		{
			get
			{
				return this._TinhThanh;
			}
			set
			{
				if ((this._TinhThanh != value))
				{
					this._TinhThanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanHuyen", DbType="NVarChar(50)")]
		public string QuanHuyen
		{
			get
			{
				return this._QuanHuyen;
			}
			set
			{
				if ((this._QuanHuyen != value))
				{
					this._QuanHuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongXa", DbType="NVarChar(50)")]
		public string PhuongXa
		{
			get
			{
				return this._PhuongXa;
			}
			set
			{
				if ((this._PhuongXa != value))
				{
					this._PhuongXa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTHonnhan", DbType="NVarChar(100)")]
		public string TTHonnhan
		{
			get
			{
				return this._TTHonnhan;
			}
			set
			{
				if ((this._TTHonnhan != value))
				{
					this._TTHonnhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(150)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this._Ghichu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiGT", DbType="NVarChar(150)")]
		public string NguoiGT
		{
			get
			{
				return this._NguoiGT;
			}
			set
			{
				if ((this._NguoiGT != value))
				{
					this._NguoiGT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLamViec", DbType="Bit")]
		public System.Nullable<bool> NoiLamViec
		{
			get
			{
				return this._NoiLamViec;
			}
			set
			{
				if ((this._NoiLamViec != value))
				{
					this._NoiLamViec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBHYT", DbType="NVarChar(50)")]
		public string SoBHYT
		{
			get
			{
				return this._SoBHYT;
			}
			set
			{
				if ((this._SoBHYT != value))
				{
					this._SoBHYT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNoiDKBHYT", DbType="NVarChar(250)")]
		public string MaNoiDKBHYT
		{
			get
			{
				return this._MaNoiDKBHYT;
			}
			set
			{
				if ((this._MaNoiDKBHYT != value))
				{
					this._MaNoiDKBHYT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoiTuong", DbType="NVarChar(50)")]
		public string DoiTuong
		{
			get
			{
				return this._DoiTuong;
			}
			set
			{
				if ((this._DoiTuong != value))
				{
					this._DoiTuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNguonGT", DbType="NVarChar(50)")]
		public string LoaiNguonGT
		{
			get
			{
				return this._LoaiNguonGT;
			}
			set
			{
				if ((this._LoaiNguonGT != value))
				{
					this._LoaiNguonGT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguonGioithieu", DbType="NVarChar(150)")]
		public string NguonGioithieu
		{
			get
			{
				return this._NguonGioithieu;
			}
			set
			{
				if ((this._NguonGioithieu != value))
				{
					this._NguonGioithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this._NgayCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(150)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDu", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> SoDu
		{
			get
			{
				return this._SoDu;
			}
			set
			{
				if ((this._SoDu != value))
				{
					this._SoDu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanHoTen", DbType="NVarChar(250)")]
		public string NguoiThanHoTen
		{
			get
			{
				return this._NguoiThanHoTen;
			}
			set
			{
				if ((this._NguoiThanHoTen != value))
				{
					this._NguoiThanHoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanQuanHe", DbType="NVarChar(150)")]
		public string NguoiThanQuanHe
		{
			get
			{
				return this._NguoiThanQuanHe;
			}
			set
			{
				if ((this._NguoiThanQuanHe != value))
				{
					this._NguoiThanQuanHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanDienThoai", DbType="NVarChar(50)")]
		public string NguoiThanDienThoai
		{
			get
			{
				return this._NguoiThanDienThoai;
			}
			set
			{
				if ((this._NguoiThanDienThoai != value))
				{
					this._NguoiThanDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThanDiaChi", DbType="NVarChar(50)")]
		public string NguoiThanDiaChi
		{
			get
			{
				return this._NguoiThanDiaChi;
			}
			set
			{
				if ((this._NguoiThanDiaChi != value))
				{
					this._NguoiThanDiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaKichHoat", DbType="Bit")]
		public System.Nullable<bool> DaKichHoat
		{
			get
			{
				return this._DaKichHoat;
			}
			set
			{
				if ((this._DaKichHoat != value))
				{
					this._DaKichHoat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTaiKhoan", DbType="NVarChar(50)")]
		public string SoTaiKhoan
		{
			get
			{
				return this._SoTaiKhoan;
			}
			set
			{
				if ((this._SoTaiKhoan != value))
				{
					this._SoTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMoTaiKhoan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayMoTaiKhoan
		{
			get
			{
				return this._NgayMoTaiKhoan;
			}
			set
			{
				if ((this._NgayMoTaiKhoan != value))
				{
					this._NgayMoTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianMoTaiKhoan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianMoTaiKhoan
		{
			get
			{
				return this._ThoiGianMoTaiKhoan;
			}
			set
			{
				if ((this._ThoiGianMoTaiKhoan != value))
				{
					this._ThoiGianMoTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Para", DbType="NVarChar(5)")]
		public string Para
		{
			get
			{
				return this._Para;
			}
			set
			{
				if ((this._Para != value))
				{
					this._Para = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
